import { ArrowRight, CalendarBlank, MapPin } from '@phosphor-icons/react'
import { featuredEvent, pastEvents } from '../data/content'

export function Events() {
  const isAvailable = Boolean(featuredEvent.url)
  return (
    <section id="events" className="scroll-scene scroll-mt-20 bg-[#001d50] py-24 text-white sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#8ec9ff]">イベント</p><h2 className="section-title mt-5 text-white">次のイベントを、<br />一緒につくろう。</h2></div><p className="max-w-xs text-sm leading-7 text-white/60">次回イベントの情報は、公式Instagramで最初にお知らせします。</p></div><article className="mt-16 grid overflow-hidden border border-white/20 lg:grid-cols-[1.1fr_0.9fr]"><div className="relative min-h-72 overflow-hidden bg-[#0056c8] p-7 sm:min-h-96 sm:p-10"><div className="event-panel absolute inset-0" aria-hidden="true" /><p className="relative inline-flex rounded-full bg-white px-3 py-1 text-xs font-black text-[#0056c8]">{featuredEvent.status}</p><p className="relative mt-24 max-w-xl text-[clamp(2rem,4.5vw,4.8rem)] font-black leading-[1.1] tracking-[-0.035em]">{featuredEvent.title}</p></div><div className="flex flex-col justify-between p-7 sm:p-10"><div><div className="space-y-4 text-sm text-white/75"><p className="flex items-center gap-3"><CalendarBlank size={19} weight="bold" className="text-[#8ec9ff]" />{featuredEvent.date}</p><p className="flex items-center gap-3"><MapPin size={19} weight="bold" className="text-[#8ec9ff]" />{featuredEvent.venue}</p></div><p className="mt-10 max-w-md text-lg leading-8">{featuredEvent.description}</p></div>{isAvailable ? <a className="mt-12 inline-flex w-fit items-center gap-3 rounded-full bg-white px-5 py-3 text-sm font-bold text-[#001d50] transition hover:bg-[#8ec9ff]" href={featuredEvent.url} target="_blank" rel="noreferrer">Instagramで最新情報を見る <ArrowRight size={18} weight="bold" /></a> : <span className="mt-12 inline-flex w-fit items-center gap-3 rounded-full border border-white/25 px-5 py-3 text-sm font-bold text-white/60">申込情報を準備中 <ArrowRight size={18} weight="bold" /></span>}</div></article>{pastEvents.length > 0 && <div className="mt-10"><p className="mb-5 text-xs font-bold tracking-[0.16em] text-white/50">これまでのイベント</p></div>}</div></section>
  )
}
